# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 1000)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_a = QtWidgets.QHBoxLayout()
        self.horizontalLayout_a.setSpacing(3)
        self.horizontalLayout_a.setObjectName("horizontalLayout_a")
        self.view_a = QtWidgets.QGraphicsView(self.centralwidget)
        self.view_a.setMinimumSize(QtCore.QSize(410, 0))
        self.view_a.setObjectName("view_a")
        self.horizontalLayout_a.addWidget(self.view_a)
        self.verticalLayout_a = QtWidgets.QVBoxLayout()
        self.verticalLayout_a.setSpacing(6)
        self.verticalLayout_a.setObjectName("verticalLayout_a")
        self.toolButton_a = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_a.setMinimumSize(QtCore.QSize(18, 18))
        self.toolButton_a.setMaximumSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(6)
        self.toolButton_a.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/small/Downloads/相机.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_a.setIcon(icon)
        self.toolButton_a.setObjectName("toolButton_a")
        self.verticalLayout_a.addWidget(self.toolButton_a)
        self.verticalScrollBar_a = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar_a.setMinimumSize(QtCore.QSize(18, 0))
        self.verticalScrollBar_a.setMaximumSize(QtCore.QSize(36, 16777215))
        self.verticalScrollBar_a.setMinimum(1)
        self.verticalScrollBar_a.setMaximum(128)
        self.verticalScrollBar_a.setProperty("value", 64)
        self.verticalScrollBar_a.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_a.setObjectName("verticalScrollBar_a")
        self.verticalLayout_a.addWidget(self.verticalScrollBar_a)
        self.verticalLayout_a.setStretch(0, 18)
        self.verticalLayout_a.setStretch(1, 280)
        self.horizontalLayout_a.addLayout(self.verticalLayout_a)
        self.horizontalLayout_a.setStretch(0, 410)
        self.horizontalLayout_a.setStretch(1, 16)
        self.gridLayout.addLayout(self.horizontalLayout_a, 0, 0, 1, 1)
        self.horizontalLayout_3d = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3d.setSpacing(3)
        self.horizontalLayout_3d.setObjectName("horizontalLayout_3d")
        self.view_3d = QtWidgets.QGraphicsView(self.centralwidget)
        self.view_3d.setObjectName("view_3d")
        self.horizontalLayout_3d.addWidget(self.view_3d)
        self.gridLayout.addLayout(self.horizontalLayout_3d, 1, 0, 1, 1)
        self.horizontalLayout_c = QtWidgets.QHBoxLayout()
        self.horizontalLayout_c.setSpacing(3)
        self.horizontalLayout_c.setObjectName("horizontalLayout_c")
        self.view_c = QtWidgets.QGraphicsView(self.centralwidget)
        self.view_c.setMinimumSize(QtCore.QSize(410, 0))
        self.view_c.setObjectName("view_c")
        self.horizontalLayout_c.addWidget(self.view_c)
        self.verticalLayout_c = QtWidgets.QVBoxLayout()
        self.verticalLayout_c.setSpacing(6)
        self.verticalLayout_c.setObjectName("verticalLayout_c")
        self.toolButton_c = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_c.setMinimumSize(QtCore.QSize(18, 18))
        self.toolButton_c.setMaximumSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(6)
        self.toolButton_c.setFont(font)
        self.toolButton_c.setIcon(icon)
        self.toolButton_c.setObjectName("toolButton_c")
        self.verticalLayout_c.addWidget(self.toolButton_c)
        self.verticalScrollBar_c = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar_c.setMinimumSize(QtCore.QSize(18, 0))
        self.verticalScrollBar_c.setMaximumSize(QtCore.QSize(36, 16777215))
        self.verticalScrollBar_c.setMinimum(1)
        self.verticalScrollBar_c.setMaximum(128)
        self.verticalScrollBar_c.setProperty("value", 64)
        self.verticalScrollBar_c.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_c.setObjectName("verticalScrollBar_c")
        self.verticalLayout_c.addWidget(self.verticalScrollBar_c)
        self.verticalLayout_c.setStretch(0, 18)
        self.verticalLayout_c.setStretch(1, 280)
        self.horizontalLayout_c.addLayout(self.verticalLayout_c)
        self.horizontalLayout_c.setStretch(0, 410)
        self.horizontalLayout_c.setStretch(1, 16)
        self.gridLayout.addLayout(self.horizontalLayout_c, 1, 1, 1, 1)
        self.horizontalLayout_s = QtWidgets.QHBoxLayout()
        self.horizontalLayout_s.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_s.setSpacing(3)
        self.horizontalLayout_s.setObjectName("horizontalLayout_s")
        self.view_s = QtWidgets.QGraphicsView(self.centralwidget)
        self.view_s.setMinimumSize(QtCore.QSize(410, 0))
        self.view_s.setObjectName("view_s")
        self.horizontalLayout_s.addWidget(self.view_s)
        self.verticalLayout_s = QtWidgets.QVBoxLayout()
        self.verticalLayout_s.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_s.setSpacing(6)
        self.verticalLayout_s.setObjectName("verticalLayout_s")
        self.toolButton_s = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_s.setMinimumSize(QtCore.QSize(18, 18))
        self.toolButton_s.setMaximumSize(QtCore.QSize(36, 36))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(6)
        self.toolButton_s.setFont(font)
        self.toolButton_s.setIcon(icon)
        self.toolButton_s.setObjectName("toolButton_s")
        self.verticalLayout_s.addWidget(self.toolButton_s)
        self.verticalScrollBar_s = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar_s.setMinimumSize(QtCore.QSize(18, 0))
        self.verticalScrollBar_s.setMaximumSize(QtCore.QSize(36, 16777215))
        self.verticalScrollBar_s.setMinimum(1)
        self.verticalScrollBar_s.setMaximum(128)
        self.verticalScrollBar_s.setProperty("value", 64)
        self.verticalScrollBar_s.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_s.setObjectName("verticalScrollBar_s")
        self.verticalLayout_s.addWidget(self.verticalScrollBar_s)
        self.verticalLayout_s.setStretch(0, 18)
        self.verticalLayout_s.setStretch(1, 280)
        self.horizontalLayout_s.addLayout(self.verticalLayout_s)
        self.horizontalLayout_s.setStretch(0, 410)
        self.horizontalLayout_s.setStretch(1, 16)
        self.gridLayout.addLayout(self.horizontalLayout_s, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuseg = QtWidgets.QMenu(self.menubar)
        self.menuseg.setObjectName("menuseg")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_main_image = QtWidgets.QAction(MainWindow)
        self.actionOpen_main_image.setObjectName("actionOpen_main_image")
        self.actionopen_seg = QtWidgets.QAction(MainWindow)
        self.actionopen_seg.setObjectName("actionopen_seg")
        self.menuFile.addAction(self.actionOpen_main_image)
        self.menuseg.addAction(self.actionopen_seg)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuseg.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ISeg_igst"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.toolButton_a.setText(_translate("MainWindow", "A"))
        self.toolButton_c.setText(_translate("MainWindow", "C"))
        self.toolButton_s.setText(_translate("MainWindow", "S"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuseg.setTitle(_translate("MainWindow", "Segmentation"))
        self.actionOpen_main_image.setText(_translate("MainWindow", "打开图像"))
        self.actionopen_seg.setText(_translate("MainWindow", "打开分割结果"))

